#!/bin/bash
# Generate Pydantic models from OpenAPI specification

set -e

echo "🔧 Generating Pydantic models from OpenAPI spec..."

# Check if datamodel-code-generator is installed
if ! command -v datamodel-codegen &> /dev/null; then
    echo "❌ datamodel-code-generator not found. Installing..."
    pip install "datamodel-code-generator[http]==0.25.1"
fi

# Create output directory if it doesn't exist
OUTPUT_DIR="functions/shared/models"
mkdir -p "$OUTPUT_DIR"

# Generate models from OpenAPI spec
datamodel-codegen \
    --input openapi.yaml \
    --output "$OUTPUT_DIR/generated.py" \
    --input-file-type openapi \
    --output-model-type pydantic_v2.BaseModel \
    --use-schema-description \
    --use-standard-collections \
    --use-annotated \
    --target-python-version 3.12 \
    --field-constraints \
    --enum-field-as-literal one \
    --capitalise-enum-members \
    --use-default \
    --use-default-kwarg \
    --collapse-root-models

echo "✅ Models generated successfully at $OUTPUT_DIR/generated.py"

# Create __init__.py to make it a package
cat > "$OUTPUT_DIR/__init__.py" << 'EOF'
"""
Auto-generated Pydantic models from OpenAPI specification.

DO NOT EDIT THIS FILE MANUALLY!
Regenerate using: ./generate-models.sh

Generated from: openapi.yaml
"""

from .generated import (
    # Dog schemas
    DogSize,
    VaccinationStatus,
    DogRequest,
    DogResponse,
    DogListResponse,

    # Owner schemas
    OwnerPreferences,
    OwnerProfileRequest,
    OwnerProfileResponse,

    # Booking schemas
    ServiceType,
    BookingStatus,
    BookingRequest,
    BookingResponse,
    BookingListResponse,
    BookingUpdateRequest,

    # Venue schemas
    OperatingHours,
    DayHours,
    VenueRequest,
    VenueResponse,
    VenueListResponse,

    # Slot schemas
    SlotBatchGenerateRequest,
    SlotBatchGenerateResponse,
    SlotAvailability,
    SlotAvailabilityResponse,
    VenueSlotsResponse,

    # Common schemas
    ErrorResponse,
    ValidationErrorResponse,
    MessageResponse,
)

__all__ = [
    # Dog schemas
    "DogSize",
    "VaccinationStatus",
    "DogRequest",
    "DogResponse",
    "DogListResponse",

    # Owner schemas
    "OwnerPreferences",
    "OwnerProfileRequest",
    "OwnerProfileResponse",

    # Booking schemas
    "ServiceType",
    "BookingStatus",
    "BookingRequest",
    "BookingResponse",
    "BookingListResponse",
    "BookingUpdateRequest",

    # Venue schemas
    "OperatingHours",
    "DayHours",
    "VenueRequest",
    "VenueResponse",
    "VenueListResponse",

    # Slot schemas
    "SlotBatchGenerateRequest",
    "SlotBatchGenerateResponse",
    "SlotAvailability",
    "SlotAvailabilityResponse",
    "VenueSlotsResponse",

    # Common schemas
    "ErrorResponse",
    "ValidationErrorResponse",
    "MessageResponse",
]
EOF

echo "✅ Created __init__.py with model exports"

# Validate the generated code with Python
python3 -c "import sys; sys.path.insert(0, 'functions/shared'); from models import DogRequest; print('✅ Generated models are valid Python code')"

echo ""
echo "📦 Models generated successfully!"
echo "   Location: $OUTPUT_DIR/"
echo "   Usage: from models import DogRequest, DogResponse, etc."
echo ""
echo "🔄 Next steps:"
echo "   1. Review generated models: cat $OUTPUT_DIR/generated.py"
echo "   2. Update Lambda functions to use models"
echo "   3. Run tests: ./run-tests.sh"
