"""
Auto-generated Pydantic models from OpenAPI specification.

DO NOT EDIT THIS FILE MANUALLY!
Regenerate using: ./generate-models.sh

Generated from: openapi.yaml
"""

from .generated import (
    # Dog schemas
    DogSize,
    VaccinationStatus,
    DogRequest,
    DogResponse,
    DogListResponse,

    # Owner schemas
    OwnerPreferences,
    OwnerProfileRequest,
    OwnerProfileResponse,

    # Booking schemas
    ServiceType,
    BookingStatus,
    BookingRequest,
    BookingResponse,
    BookingListResponse,
    BookingUpdateRequest,

    # Venue schemas
    OperatingHours,
    DayHours,
    VenueRequest,
    VenueResponse,
    VenueListResponse,

    # Slot schemas
    SlotBatchGenerateRequest,
    SlotBatchGenerateResponse,
    SlotAvailability,
    SlotAvailabilityResponse,
    VenueSlotsResponse,

    # Common schemas
    ErrorResponse,
    ValidationErrorResponse,
    MessageResponse,
)

__all__ = [
    # Dog schemas
    "DogSize",
    "VaccinationStatus",
    "DogRequest",
    "DogResponse",
    "DogListResponse",

    # Owner schemas
    "OwnerPreferences",
    "OwnerProfileRequest",
    "OwnerProfileResponse",

    # Booking schemas
    "ServiceType",
    "BookingStatus",
    "BookingRequest",
    "BookingResponse",
    "BookingListResponse",
    "BookingUpdateRequest",

    # Venue schemas
    "OperatingHours",
    "DayHours",
    "VenueRequest",
    "VenueResponse",
    "VenueListResponse",

    # Slot schemas
    "SlotBatchGenerateRequest",
    "SlotBatchGenerateResponse",
    "SlotAvailability",
    "SlotAvailabilityResponse",
    "VenueSlotsResponse",

    # Common schemas
    "ErrorResponse",
    "ValidationErrorResponse",
    "MessageResponse",
]
