# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-10-16T20:57:18+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Annotated, Any, Optional

from pydantic import AwareDatetime, BaseModel, Field


class DogSize(Enum):
    """
    Dog size classification
    """

    SMALL = 'SMALL'
    MEDIUM = 'MEDIUM'
    LARGE = 'LARGE'
    XLARGE = 'XLARGE'


class VaccinationStatus(Enum):
    """
    Dog vaccination status
    """

    VACCINATED = 'VACCINATED'
    NOT_VACCINATED = 'NOT_VACCINATED'


class DogRequest(BaseModel):
    name: Annotated[
        str,
        Field(description="Dog's name", examples=['Max'], max_length=100, min_length=1),
    ]
    breed: Annotated[
        str,
        Field(
            description='Dog breed',
            examples=['Golden Retriever'],
            max_length=100,
            min_length=1,
        ),
    ]
    date_of_birth: Annotated[
        date,
        Field(
            description="Dog's date of birth (ISO 8601 format, cannot be in the future)",
            examples=['2020-05-15'],
        ),
    ]
    size: DogSize
    vaccination_status: VaccinationStatus
    microchipped: Annotated[
        Optional[bool],
        Field(default=False, description='Whether the dog is microchipped'),
    ]
    special_needs: Annotated[
        Optional[list[str]],
        Field(
            default=[],
            description='List of special needs or requirements',
            examples=[['separation anxiety', 'food allergies']],
        ),
    ]
    medical_notes: Annotated[
        Optional[str],
        Field(
            default='',
            description='Medical history and notes',
            examples=['Allergic to chicken'],
        ),
    ]
    behavior_notes: Annotated[
        Optional[str],
        Field(
            default='',
            description='Behavioral observations and notes',
            examples=['Friendly with other dogs'],
        ),
    ]
    favorite_activities: Annotated[
        Optional[str],
        Field(
            default='', description='Preferred activities', examples=['Fetch, swimming']
        ),
    ]


class DogResponse(BaseModel):
    id: Annotated[
        str,
        Field(
            description='Unique dog identifier',
            examples=['dog-123e4567-e89b-12d3-a456-426614174000'],
        ),
    ]
    name: Annotated[str, Field(examples=['Max'])]
    breed: Annotated[str, Field(examples=['Golden Retriever'])]
    date_of_birth: Annotated[date, Field(examples=['2020-05-15'])]
    age: Annotated[
        str,
        Field(
            description='Calculated age from date of birth',
            examples=['4 years, 3 months'],
        ),
    ]
    size: DogSize
    vaccination_status: VaccinationStatus
    microchipped: Optional[bool] = None
    special_needs: Optional[list[str]] = None
    medical_notes: Optional[str] = None
    behavior_notes: Optional[str] = None
    favorite_activities: Optional[str] = None
    owner_id: Annotated[
        str,
        Field(
            description='Firebase user ID of the owner', examples=['firebase-user-123']
        ),
    ]
    created_at: Annotated[AwareDatetime, Field(examples=['2024-01-15T10:30:00Z'])]
    updated_at: Annotated[AwareDatetime, Field(examples=['2024-01-15T10:30:00Z'])]


class DogListResponse(BaseModel):
    dogs: list[DogResponse]
    count: Annotated[int, Field(description='Number of dogs returned', examples=[3])]


class PreferredCommunication(Enum):
    EMAIL = 'email'
    SMS = 'sms'
    PUSH = 'push'


class OwnerPreferences(BaseModel):
    notifications: Annotated[
        Optional[bool], Field(default=True, description='Enable push notifications')
    ]
    marketing_emails: Annotated[
        Optional[bool],
        Field(default=False, description='Receive marketing communications'),
    ]
    preferred_communication: Optional[PreferredCommunication] = 'email'


class OwnerProfileRequest(BaseModel):
    preferences: Optional[OwnerPreferences] = None
    notification_settings: Annotated[
        Optional[dict[str, Any]],
        Field(default=None, description='Granular notification settings'),
    ]


class OwnerProfileResponse(BaseModel):
    user_id: Annotated[
        str,
        Field(description='Firebase user ID (not PII)', examples=['firebase-user-123']),
    ]
    preferences: OwnerPreferences
    notification_settings: Optional[dict[str, Any]] = None
    registration_complete: Annotated[
        Optional[bool],
        Field(
            default=None,
            description='Whether profile setup is complete',
            examples=[True],
        ),
    ]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ServiceType(Enum):
    """
    Type of service being booked
    """

    DAYCARE = 'daycare'
    BOARDING = 'boarding'
    GROOMING = 'grooming'
    WALKING = 'walking'
    TRAINING = 'training'


class BookingStatus(Enum):
    """
    Current status of the booking
    """

    PENDING = 'pending'
    CONFIRMED = 'confirmed'
    IN_PROGRESS = 'in_progress'
    COMPLETED = 'completed'
    CANCELLED = 'cancelled'


class BookingRequest(BaseModel):
    dog_id: Annotated[
        str,
        Field(
            description='ID of the dog being booked',
            examples=['dog-123e4567-e89b-12d3-a456-426614174000'],
        ),
    ]
    venue_id: Annotated[
        str,
        Field(
            description='ID of the venue',
            examples=['venue-123e4567-e89b-12d3-a456-426614174000'],
        ),
    ]
    service_type: ServiceType
    start_time: Annotated[
        AwareDatetime,
        Field(
            description='Booking start time (ISO 8601)',
            examples=['2024-01-20T09:00:00Z'],
        ),
    ]
    end_time: Annotated[
        AwareDatetime,
        Field(
            description='Booking end time (ISO 8601, must be after start_time)',
            examples=['2024-01-20T17:00:00Z'],
        ),
    ]
    special_instructions: Annotated[
        Optional[str],
        Field(
            default='',
            description='Special instructions for the booking',
            examples=['Please use the special harness'],
        ),
    ]


class BookingResponse(BaseModel):
    id: Annotated[str, Field(examples=['booking-123e4567-e89b-12d3-a456-426614174000'])]
    dog_id: str
    owner_id: str
    venue_id: str
    service_type: ServiceType
    start_time: AwareDatetime
    end_time: AwareDatetime
    status: BookingStatus
    price: Annotated[
        float,
        Field(
            description='Price in GBP calculated from service type and duration',
            examples=[120.0],
        ),
    ]
    special_instructions: Optional[str] = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class BookingListResponse(BaseModel):
    bookings: list[BookingResponse]
    count: Annotated[int, Field(examples=[5])]


class BookingUpdateRequest(BaseModel):
    service_type: Optional[ServiceType] = None
    start_time: Optional[AwareDatetime] = None
    end_time: Optional[AwareDatetime] = None
    status: Optional[BookingStatus] = None
    special_instructions: Optional[str] = None


class DayHours(BaseModel):
    open: Annotated[
        Optional[bool],
        Field(default=True, description='Whether the venue is open on this day'),
    ]
    start: Annotated[
        Optional[str],
        Field(
            default=None,
            description='Opening time in HH:MM format (24-hour)',
            examples=['09:00'],
            pattern='^([01]\\d|2[0-3]):([0-5]\\d)$',
        ),
    ]
    end: Annotated[
        Optional[str],
        Field(
            default=None,
            description='Closing time in HH:MM format (24-hour)',
            examples=['18:00'],
            pattern='^([01]\\d|2[0-3]):([0-5]\\d)$',
        ),
    ]


class SlotBatchGenerateRequest(BaseModel):
    venue_id: Annotated[
        str,
        Field(
            description='Venue ID to generate slots for',
            examples=['venue-123e4567-e89b-12d3-a456-426614174000'],
        ),
    ]
    start_date: Annotated[
        date,
        Field(
            description='Start date for slot generation (YYYY-MM-DD)',
            examples=['2024-01-01'],
        ),
    ]
    end_date: Annotated[
        date,
        Field(
            description='End date for slot generation (YYYY-MM-DD, must be >= start_date)',
            examples=['2024-01-31'],
        ),
    ]


class DateRange(BaseModel):
    start: Optional[date] = None
    end: Optional[date] = None


class SlotBatchGenerateResponse(BaseModel):
    message: Annotated[str, Field(examples=['Slots generated successfully'])]
    venue_id: str
    date_range: DateRange
    slots_created: Annotated[
        int, Field(description='Total number of slots created', examples=[240])
    ]


class SlotAvailability(BaseModel):
    time: Annotated[
        str,
        Field(
            description='Time slot in HH:MM format',
            examples=['09:00'],
            pattern='^([01]\\d|2[0-3]):([0-5]\\d)$',
        ),
    ]
    available: Annotated[
        int, Field(description='Available capacity for this slot', examples=[15])
    ]
    total: Annotated[
        int, Field(description='Total capacity for this slot', examples=[20])
    ]


class SlotAvailabilityResponse(BaseModel):
    date: date
    venues_with_availability: Annotated[
        dict[str, list[SlotAvailability]],
        Field(description='Map of venue IDs to their available slots'),
    ]
    total_venues: Annotated[
        int, Field(description='Number of venues with availability', examples=[3])
    ]


class Slot(BaseModel):
    """
    Detailed slot information
    """

    venue_date: Optional[str] = None
    slot_time: Optional[str] = None
    venue_id: Optional[str] = None
    date: Optional[str] = None
    available_capacity: Optional[int] = None
    total_capacity: Optional[int] = None
    booked_count: Optional[int] = None
    created_at: Optional[AwareDatetime] = None


class VenueSlotsResponse(BaseModel):
    venue_id: str
    date_range: DateRange
    slots: Annotated[
        dict[str, list[Slot]], Field(description='Map of dates to slot arrays')
    ]


class ErrorResponse(BaseModel):
    error: Annotated[
        str,
        Field(description='Human-readable error message', examples=['Dog not found']),
    ]


class Error(BaseModel):
    loc: Annotated[
        Optional[list[str]],
        Field(default=None, description='Location of the error in the request'),
    ]
    msg: Annotated[Optional[str], Field(default=None, description='Error message')]
    type: Annotated[Optional[str], Field(default=None, description='Error type')]


class ValidationErrorResponse(BaseModel):
    errors: list[Error]


class MessageResponse(BaseModel):
    message: Annotated[str, Field(examples=['Operation successful'])]


class OperatingHours(BaseModel):
    """
    Operating hours for each day of the week
    """

    monday: Optional[DayHours] = None
    tuesday: Optional[DayHours] = None
    wednesday: Optional[DayHours] = None
    thursday: Optional[DayHours] = None
    friday: Optional[DayHours] = None
    saturday: Optional[DayHours] = None
    sunday: Optional[DayHours] = None


class VenueRequest(BaseModel):
    name: Annotated[
        str,
        Field(
            description='Venue name',
            examples=['Happy Paws Downtown'],
            max_length=200,
            min_length=1,
        ),
    ]
    address: Annotated[
        str,
        Field(
            description='Full venue address',
            examples=['123 Main St, London, UK'],
            min_length=1,
        ),
    ]
    latitude: Annotated[
        float,
        Field(
            description='Latitude coordinate (WGS84)',
            examples=[51.5074],
            ge=-90.0,
            le=90.0,
        ),
    ]
    longitude: Annotated[
        float,
        Field(
            description='Longitude coordinate (WGS84)',
            examples=[-0.1278],
            ge=-180.0,
            le=180.0,
        ),
    ]
    capacity: Annotated[
        int,
        Field(
            description='Maximum number of dogs that can be accommodated simultaneously',
            examples=[20],
            ge=1,
        ),
    ]
    operating_hours: OperatingHours
    services: Annotated[
        Optional[list[ServiceType]],
        Field(default=['daycare'], description='Services offered at this venue'),
    ]
    slot_duration: Annotated[
        Optional[int],
        Field(
            default=60,
            description='Duration of each time slot in minutes',
            ge=15,
            le=240,
        ),
    ]


class VenueResponse(BaseModel):
    id: Annotated[str, Field(examples=['venue-123e4567-e89b-12d3-a456-426614174000'])]
    name: str
    address: str
    latitude: Annotated[
        float, Field(description='Latitude coordinate (WGS84)', examples=[51.5074])
    ]
    longitude: Annotated[
        float, Field(description='Longitude coordinate (WGS84)', examples=[-0.1278])
    ]
    capacity: int
    operating_hours: OperatingHours
    services: Optional[list[ServiceType]] = None
    slot_duration: Optional[int] = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class VenueListResponse(BaseModel):
    venues: list[VenueResponse]
    count: Annotated[int, Field(examples=[10])]
